### ISSUE TITLE
Find Covid stats API

### ISSUE THREAD

**Issue by kunalpa** [comp426-2022-spring/a99-atlas#4]

**Comment by kunalpa** [comment]
From World Health Organization -- https://www.who.int/data/gho/info/athena-api-examples

**Comment by kchange7** [comment]
Link to Github with COVID data: https://github.com/owid/covid-19-data/tree/master/public/data

**Comment by nymanka** [comment]
https://raw.githubusercontent.com/samayo/country-json/master/src/country-by-population.json

**Comment by kchange7** [comment]
Vaccination: https://github.com/owid/covid-19-data/blob/master/public/data/internal/megafile--vaccinations.json
Deaths: https://github.com/owid/covid-19-data/blob/master/public/data/internal/megafile--deaths.json
Cases: https://github.com/owid/covid-19-data/blob/master/public/data/internal/megafile--cases-tests.json
